/*
    ,--.                     ,--.     ,--.  ,--.
  ,-'  '-.,--.--.,--,--.,---.|  |,-.,-'  '-.`--' ,---. ,--,--,      Copyright 2024
  '-.  .-'|  .--' ,-.  | .--'|     /'-.  .-',--.| .-. ||      \   Tracktion Software
    |  |  |  |  \ '-'  \ `--.|  \  \  |  |  |  |' '-' '|  ||  |       Corporation
    `---' `--'   `--`--'`---'`--'`--' `---' `--' `---' `--''--'    www.tracktion.com

    Tracktion Engine uses a GPL/commercial licence - see LICENCE.md for details.
*/

namespace tracktion { inline namespace engine
{

//==============================================================================
/**
    A non-persistent grouping of Clips that lets several clips be treated as one item.

    A CollectionClip doesn't hold any source material itself — it's a TrackItem whose
    position is simply the bounding time range (range) of the clips it references, kept
    up to date by updateStartAndEnd. It is a view/edit convenience: selecting, moving or
    dragging the collection acts on all member clips together.

    Two flavours exist, distinguished by isGroupCollection():
    - Group collections gather clips that share a group ID (Clip::setGroup), regardless
      of track. These are rebuilt from the clips' group IDs and are not stored in the
      ValueTree.
    - Folder collections (getFolderTrack() != nullptr) represent all the clips on the
      child tracks of a FolderTrack, so a collapsed folder shows a single merged clip.

    Because it is derived on the fly, a CollectionClip must not be persisted; it is
    regenerated by ClipTrack/FolderTrack whenever the underlying clips change.

    @see TrackItem, Clip::setGroup, ClipTrack, FolderTrack
*/
class CollectionClip   : public TrackItem
{
public:
    CollectionClip (Track&);
    ~CollectionClip() override;

    using Ptr = juce::ReferenceCountedObjectPtr<CollectionClip>;
    using Array = juce::ReferenceCountedArray<CollectionClip>;

    void addClip (Clip*);
    void removeClip (Clip*);
    bool removeClip (EditItemID);
    bool containsClip (Clip* clip) const noexcept       { return clips.contains (clip); }

    juce::String getName() const override;

    ClipPosition getPosition() const override           { return { range, TimeDuration() }; }
    Track* getTrack() const override                    { return track; }

    bool moveToTrack (Track&);
    void updateStartAndEnd();

    FolderTrack* getFolderTrack() const noexcept;

    juce::String getSelectableDescription() override    { return TRANS("Collection clips"); }
    int getNumClips() const noexcept                    { return clips.size(); }
    Clip::Ptr getClip (int index) const                 { return clips[index]; }
    const Clip::Array& getClips() const noexcept        { return clips; }

    void setDragging (bool nowDragging) noexcept        { dragging = nowDragging; }
    bool isDragging() const noexcept                    { return dragging; }


    EditItemID getGroupID() const noexcept              { return groupID; }
    void setGroupID (EditItemID newGroupID)             { groupID = newGroupID; }

    bool isGroupCollection() const                      { return getFolderTrack() == nullptr; }

    TimeRange range;

private:
    Track* track;
    Clip::Array clips;
    bool dragging = false;
    EditItemID groupID;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (CollectionClip)
};

}} // namespace tracktion { inline namespace engine
